version: "3.8"
services:
  server:
    container_name: bamboo-server
    image: atlassian/bamboo-server:8.2.3-jdk11
    ports:
      - 54663:54663
      - 8085:8085
    volumes:
      - ./application-data:/var/atlassian/application-data/bamboo
    init: true # Recommended by Atlassian to properly reap zombie processes
