version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.346.2-lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      # - 50000:50000
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock # docker build 시 필요
