version: '3.8'

services:

  jenkins-master:
    container_name: jenkins-master
    image: jenkins/jenkins:2.346.2-lts-jdk11
    privileged: true
    user: root
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_home:/var/jenkins_home
  
  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins/ssh-slave:jdk11
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICwVRtUI9bMYxF0zuAt51/2ogofRxLbui46vnfuAygtX imcxsu@gmail.com"
