version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.346.2-lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_home:/var/jenkins_home
